name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run server tests with Coverage
      run: |
        coverage run --source=./src/server --omit=src/server/memory/base.py -m unittest
        coverage report -m --fail-under=95
    - name: Run client tests with Coverage
      run: |
        coverage run --source=./src/client -m unittest
        coverage report -m --fail-under=60
